CREATE TABLE CUSTOMERS (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR NOT NULL,
    MIDDLE_NAME VARCHAR,
    LAST_NAME VARCHAR NOT NULL,
    BIRTH_DATE DATE,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EMAILS (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT,
    EMAIL_ADDRESS VARCHAR NOT NULL,
    IS_PRIMARY BIT DEFAULT 0,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_EMAIL_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE PHONES (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT,
    PHONE_NUMBER VARCHAR NOT NULL,
    PHONE_TYPE VARCHAR NOT NULL,
    IS_PRIMARY BIT DEFAULT 0,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PHONES_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE ADDRESSES (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT,
    STREET VARCHAR NOT NULL,
    CITY_NAME VARCHAR NOT NULL,
    STATE_NAME VARCHAR NOT NULL,
    ZIP_CODE VARCHAR NOT NULL,
    IS_PRIMARY BIT DEFAULT 0,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ADDRESSES_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE ACCOUNTS (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT,
    ACCOUNT_TYPE VARCHAR NOT NULL,
    IS_ACTIVE BIT DEFAULT 1,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCOUNTS_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ACCOUNT_ID INT,
    TRANSACTION_TYPE VARCHAR NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TRANSACTION_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION VARCHAR,
    CONSTRAINT FK_TRANSACTIONS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);