CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE EMAILS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE PHONES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    PHONE_TYPE VARCHAR(50) NOT NULL,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE ADDRESSES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    STREET VARCHAR(255) NOT NULL,
    CITY_NAME VARCHAR(100) NOT NULL,
    STATE_NAME VARCHAR(100),
    ZIP_CODE VARCHAR(20),
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE ACCOUNTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID INT,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);

